import 'server-only';
import{cookies}from'next/headers';
import{createServerClient}from'@supabase/ssr';
import{createClient}from'@supabase/supabase-js';
import{NextResponse}from'next/server';
import{timingSafeEqual}from'node:crypto';
import{initialState,type AppState}from'./domain';
export const cloudConfigured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY&&process.env.SUPABASE_SERVICE_ROLE_KEY);
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export async function authClient(){const jar=await cookies();return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{cookies:{getAll:()=>jar.getAll(),setAll:all=>{try{all.forEach(({name,value,options})=>jar.set(name,value,options));}catch{}}}});}
export async function requireUser(){if(!cloudConfigured())throw new HttpError(503,'A nuvem ainda não foi configurada.');const client=await authClient(),{data,error}=await client.auth.getUser();if(error||!data.user)throw new HttpError(401,'Entre na sua conta para continuar.');return data.user;}
export function admin(){if(!cloudConfigured())throw new HttpError(503,'A nuvem ainda não foi configurada.');return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function documentFor(userId:string){const {data,error}=await admin().from('forge_documents').select('state,version').eq('user_id',userId).maybeSingle();if(error)throw new HttpError(503,'Não foi possível acessar seus dados. Confira a configuração do banco.');return data as {state:AppState;version:number}|null;}
export async function saveDocument(userId:string,state:AppState,version:number){const db=admin();if(version===0){const{error}=await db.from('forge_documents').insert({user_id:userId,state,version:1});if(error?.code==='23505')throw new HttpError(409,'Sua conta mudou em outro dispositivo. Recarregue antes de continuar.');if(error)throw new HttpError(503,'Não foi possível salvar na nuvem.');return 1;}const{data,error}=await db.from('forge_documents').update({state,version:version+1,updated_at:new Date().toISOString()}).eq('user_id',userId).eq('version',version).select('version').maybeSingle();if(error)throw new HttpError(503,'Não foi possível salvar na nuvem.');if(!data)throw new HttpError(409,'Sua conta mudou em outro dispositivo. Recarregue antes de continuar.');return data.version as number;}
export async function mutateDocument(userId:string,fn:(s:AppState)=>AppState){for(let i=0;i<3;i++){const doc=await documentFor(userId);try{const next=fn(doc?.state||initialState());await saveDocument(userId,next,doc?.version||0);return next;}catch(e){if(!(e instanceof HttpError&&e.status===409)||i===2)throw e;}}throw new HttpError(409,'Tente novamente.');}
export function sameOrigin(req:Request){const origin=req.headers.get('origin'),allowed=new Set([new URL(req.url).origin,...(process.env.NEXT_PUBLIC_APP_URL?[new URL(process.env.NEXT_PUBLIC_APP_URL).origin]:[])]);if(!origin||!allowed.has(origin))throw new HttpError(403,'Origem não autorizada.');}
export async function jsonBody(req:Request,max=256000){const length=Number(req.headers.get('content-length')||0);if(length>max)throw new HttpError(413,'Pedido muito grande.');const reader=req.body?.getReader();if(!reader)return{};const chunks:Uint8Array[]=[];let total=0;while(true){const r=await reader.read();if(r.done)break;total+=r.value.byteLength;if(total>max){await reader.cancel();throw new HttpError(413,'Pedido muito grande.');}chunks.push(r.value);}try{return JSON.parse(Buffer.concat(chunks).toString());}catch{throw new HttpError(400,'JSON inválido.');}}
export function fail(e:unknown){if(e instanceof HttpError)return NextResponse.json({error:e.message},{status:e.status});if(e instanceof Error&&e.name==='ZodError')return NextResponse.json({error:'Confira os dados informados.'},{status:400});return NextResponse.json({error:'Não foi possível concluir a operação.'},{status:500});}
export function secretMatches(value:string|null,secret:string|undefined){if(!value||!secret)return false;const a=Buffer.from(value),b=Buffer.from(secret);return a.length===b.length&&timingSafeEqual(a,b);}
