/* FORGE — vanilla JS prototype. Device-local demo data, no remote services. */
(() => {
  'use strict';
  const {icon,esc,money,dots,progress,art,badge,gauge}=ForgeUI;
  const $=s=>document.querySelector(s), KEY='forge.prototype.v1';
  const localDay=()=>new Date().toLocaleDateString('en-CA');
  const seed=()=>({version:1,name:'Davi',handle:'davi',city:'Jacareí, SP',xp:5840,weekXp:640,streak:7,lastAction:localDay(),day:localDay(),theme:'dark',notifications:false,month:'2026-09',
    habits:[{id:'train',name:'Treinar 45 min',reward:60,art:'dumbbell',done:false},{id:'study',name:'Estudar 30 min',reward:40,art:'book',done:true},{id:'water',name:'Beber 2 L de água',reward:20,art:'flame',done:true}],
    tasks:[{id:'t1',name:'Revisar o projeto do SaaS',done:true},{id:'t2',name:'Organizar a semana',done:true},{id:'t3',name:'Revisar anotações da FATEC',done:true},{id:'t4',name:'Finalizar a landing page',done:false},{id:'t5',name:'Planejar o próximo sprint',done:false}],
    goals:[{id:'saas',name:'Lançar meu SaaS',category:'Carreira',deadline:'2026-09-30',target:100,current:68,unit:'%',reward:500,art:'laptop',completed:false},{id:'save',name:'Guardar R$ 500',category:'Finanças',deadline:'2026-09-30',target:500,current:240,unit:'R$',reward:300,art:'coins',completed:false},{id:'fatec',name:'Estudar para a FATEC',category:'Estudos',deadline:'2026-09-20',target:5,current:3,unit:'módulos',reward:200,art:'stack',completed:false}],
    transactions:[{id:'salary',name:'Salário',amount:3200,type:'income',category:'Salário',date:'2026-09-05'},{id:'market',name:'Mercado',amount:120,type:'expense',category:'Comida',date:'2026-09-14'},{id:'food',name:'Alimentação',amount:300,type:'expense',category:'Comida',date:'2026-09-10'},{id:'bus',name:'Transporte',amount:180,type:'expense',category:'Transporte',date:'2026-09-09'},{id:'course',name:'Curso',amount:250,type:'expense',category:'Estudos',date:'2026-09-08'},{id:'fun',name:'Lazer',amount:160,type:'expense',category:'Lazer',date:'2026-09-07'},{id:'other',name:'Outras despesas',amount:350,type:'expense',category:'Outros',date:'2026-09-06'}]});
  let state;try{const saved=JSON.parse(localStorage.getItem(KEY));state=saved?.version===1&&Array.isArray(saved.habits)&&Array.isArray(saved.goals)&&Array.isArray(saved.transactions)?saved:seed();}catch{state=seed();}
  if(state.day!==localDay()){state.day=localDay();state.habits.forEach(h=>h.done=false);state.tasks.forEach(t=>t.done=false);}
  let route='',toastTimer,categoryFilter=null;
  const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
  const animate=(el,vars)=>window.gsap&&!reduced()?gsap.to(el,vars):null;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('Alteração aplicada. Não foi possível salvar neste navegador.');}}
  function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;animate('#toast',{opacity:1,y:0,duration:.25});if(!window.gsap||reduced())$('#toast').style.opacity=1;toastTimer=setTimeout(()=>{if(!animate('#toast',{opacity:0,y:8,duration:.25}))$('#toast').style.opacity=0;},3200);}
  const level=()=>Math.floor(state.xp/500)+1;
  const title=()=>level()<=5?'Iniciante':level()<=10?'Construtor':level()<=15?'Devbuilder':level()<=20?'Executor':'Arquiteto';
  function earn(amount){state.xp=Math.max(0,state.xp+amount);state.weekXp=Math.max(0,state.weekXp+amount);if(amount>0&&state.lastAction!==localDay()){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);state.streak=state.lastAction===yesterday.toLocaleDateString('en-CA')?state.streak+1:1;state.lastAction=localDay();state.xp+=10;state.weekXp+=10;}}
  const prettyDate=date=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','');
  const monthLabel=()=>new Date(state.month+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long'});
  const transactions=()=>state.transactions.filter(t=>t.date.startsWith(state.month));
  function finances(){const all=transactions(),income=all.filter(t=>t.type==='income').reduce((a,t)=>a+t.amount,0),expense=all.filter(t=>t.type==='expense').reduce((a,t)=>a+t.amount,0);return{income,expense,balance:income-expense};}
  const stat=(label,value,type)=>`<div class="panel stat-card"><span class="stat-icon">${icon(type)}</span><div><small>${label}</small><strong>${esc(value)}</strong></div></div>`;
  const achievements=()=>[{name:'Primeiro passo',criterion:'1 registro',type:'dumbbell',unlocked:state.transactions.length>0},{name:'Em movimento',criterion:'3 dias',type:'book',unlocked:state.streak>=3},{name:'Uma semana',criterion:'7 dias',type:'flame',unlocked:state.streak>=7},{name:'Construtor',criterion:'Nível 5',type:'stack',unlocked:level()>=5},{name:'Consistência',criterion:'10 dias',type:'flame',unlocked:state.streak>=10},{name:'Executor',criterion:'Nível 20',type:'laptop',unlocked:level()>=20}];
  const badgeButton=(b,i,withLabels=false)=>`<button class="badge-button" data-badge="${i}" aria-label="${esc(b.name)}, ${b.unlocked?'desbloqueada':'bloqueada'}">${badge(b.type,!b.unlocked)}${withLabels?`<span class="badge-name">${b.name}</span><small>${b.criterion}</small>`:''}</button>`;
  function home(){const f=finances(),hDone=state.habits.filter(h=>h.done).length,tDone=state.tasks.filter(t=>t.done).length;return `
    <section class="hero home-hero" aria-label="Sua sequência"><img class="hero-photo" src="assets/home-hero.png" alt="Atleta em silhueta com iluminação teal"><div class="home-copy"><p class="hero-eyebrow">Sua sequência</p><h1>CADA DIA<br>CONTA.</h1><button class="white-button" data-action="register">Registrar ação</button></div><svg class="hero-arc" viewBox="0 0 160 275" aria-hidden="true"><path d="M157-15C-1 78-7 210 161 282"/><circle cx="42" cy="141" r="4.5" fill="white"/></svg><div class="hero-streak">${dots(String(state.streak).padStart(2,'0'))}<p>dias<br>seguidos</p></div><div class="streak-footer"><div class="streak-days">${Array.from({length:10},(_,i)=>`<i class="${i<Math.min(state.streak,10)?'lit':''}"></i>`).join('')}</div><small>Próximo marco: ${state.streak<10?10:state.streak<21?21:30} dias</small></div></section>
    <section class="stats-grid" aria-label="Resumo do dia">${stat('Saldo atual',money(f.balance),'wallet')}${stat('XP da semana','+'+state.weekXp+' XP','star')}<button class="stat-card panel" data-action="tasks"><span class="stat-icon">${icon('checkbox')}</span><span><small>Tarefas do dia</small><strong>${tDone}/${state.tasks.length}</strong></span></button>${stat('Hábitos',hDone+'/'+state.habits.length,'bars')}</section>
    <section class="panel today-panel"><div class="today-heading"><h2>Hoje</h2><button class="text-button" data-action="habits">Ver todos ${icon('chevron')}</button></div>${state.habits.slice(0,2).map(h=>`<button class="activity-row ${h.done?'done':''}" data-habit="${h.id}" aria-pressed="${h.done}"><span class="checkbox">${h.done?icon('check'):''}</span>${art(h.art)}<span class="activity-name">${esc(h.name)}</span><span class="reward">+${h.reward} XP</span>${icon('chevron')}</button>`).join('')}</section>
    <section class="panel achievements-panel"><div class="section-heading"><h2>Conquistas recentes</h2><a class="text-button" href="#perfil">Ver todas ${icon('chevron')}</a></div><div class="badges-row">${achievements().slice(0,3).map((b,i)=>badgeButton(b,i)).join('')}</div></section>`;}
  function goals(){return `<section class="hero goals-hero"><img class="hero-photo" src="assets/workout-hero.png" alt="Atleta na academia com iluminação cinematográfica"><div class="home-copy"><h1>CONSTRUA<br>SUA MELHOR<br>VERSÃO.</h1><p>Um objetivo de cada vez.</p></div></section><section class="panel level-panel"><div class="level-title"><div><h2>Seu nível</h2><p>${title()}</p></div><span class="round-icon">${icon('bars')}</span></div><div class="level-number">${dots(level())}</div>${progress((state.xp%500)/5)}<div class="progress-meta"><span>${state.xp%500} / 500 XP</span><span>Faltam ${500-state.xp%500} XP</span></div></section><div class="section-heading"><h2>Suas metas</h2><button class="text-button" data-action="new-goal">Criar meta ${icon('plus')}</button></div><section class="goal-list">${state.goals.map(g=>`<button class="panel goal-row" data-goal="${g.id}"><span class="goal-art">${art(g.art)}</span><span class="goal-info"><span class="goal-top"><span class="goal-name">${esc(g.name)}</span><span class="reward">+${g.reward} XP</span></span><small>${esc(g.category)} · ${prettyDate(g.deadline)}</small><span class="goal-progress">${progress(g.current/g.target*100)}<span>${g.unit==='R$'?money(g.current)+' / '+g.target:g.unit==='%'?Math.round(g.current/g.target*100)+'%':g.current+' / '+g.target+' '+esc(g.unit)}</span></span></span>${icon('chevron')}</button>`).join('')||'<p class="empty-state">Sua próxima conquista começa com uma meta.</p>'}</section>`;}
  function finance(){const f=finances(),used=f.income?Math.round(f.expense/f.income*100):0;const cats=[['Comida','fork'],['Transporte','bus'],['Estudos','book'],['Lazer','game'],['Outros','more']];const list=transactions().filter(t=>!categoryFilter||t.category===categoryFilter).sort((a,b)=>b.date.localeCompare(a.date));return `<section class="finance-top"><div class="panel finance-small"><div class="card-label">Entradas ${icon('arrow')}</div>${dots(money(f.income))}<div class="tiny-bars" aria-hidden="true">${Array.from({length:23},(_,i)=>`<i class="${i<16?'lit':''}"></i>`).join('')}</div></div><div class="panel finance-small"><div class="card-label">Orçamento usado ${icon('pie')}</div>${gauge(used)}</div></section><section class="panel balance-panel"><div class="balance-header"><div><h2>Saldo disponível</h2><p style="text-transform:capitalize">${monthLabel()} de ${state.month.slice(0,4)}</p></div><span class="reserve-label">Saldo ${icon('coins')}</span></div><div class="balance-bottom">${dots(money(f.balance))}<div class="capsules" role="img" aria-label="${f.income?Math.max(0,Math.round(f.balance/f.income*100)):0}% das entradas disponíveis">${Array.from({length:6},(_,i)=>`<span class="capsule"><i class="liquid" style="--fill:${Math.min(100,Math.max(0,((f.income?f.balance/f.income:0)*6-i)*100))}%"></i></span>`).join('')}</div></div></section><section class="cashflow">${stat('Entradas',money(f.income),'wallet')}${stat('Saídas',money(f.expense),'down')}</section><div class="section-heading"><h2>Categorias</h2><button class="text-button" data-action="clear-category">Ver todas ${icon('chevron')}</button></div><section class="category-strip" aria-label="Filtrar transações">${cats.map(([name,i])=>`<button class="category-pill ${categoryFilter===name||(!categoryFilter&&name==='Outros')?'selected':''}" data-category="${name}" aria-pressed="${categoryFilter===name}">${icon(i)}<span>${name}</span>${dots(money(transactions().filter(t=>t.type==='expense'&&t.category===name).reduce((sum,t)=>sum+t.amount,0)))}</button>`).join('')}</section><div class="section-heading"><h2>${categoryFilter||'Transações'}</h2><button class="add-pill" data-action="transaction">${icon('plus')}Adicionar</button></div><section class="transactions">${list.map(t=>`<div class="panel transaction-row"><span class="round-icon">${icon(t.type==='income'?'briefcase':t.category==='Comida'?'cart':'wallet')}</span><span class="transaction-name">${esc(t.name)} <small>· ${prettyDate(t.date)}</small></span><span class="transaction-value ${t.type==='income'?'income':''}">${t.type==='income'?'+':'−'} ${money(t.amount)}</span></div>`).join('')||'<p class="empty-state">Nenhuma transação neste período.</p>'}</section>`;}
  function profile(){return `<section class="hero profile-hero"><img class="hero-photo" src="assets/home-hero.png" alt=""><span class="avatar"><img src="assets/home-hero.png" alt="Avatar ilustrativo do perfil"></span><h1>${esc(state.name)}</h1><p class="handle">@${esc(state.handle)} · ${esc(state.city)}</p><span class="level-pill">${title()} · Nível ${level()}</span>${progress((state.xp%500)/5)}<div class="progress-meta">${state.xp%500} / 500 XP</div></section><section class="profile-stats">${[[String(state.streak).padStart(2,'0'),'Sequência'],[String(achievements().filter(b=>b.unlocked).length).padStart(2,'0'),'Conquistas'],[state.xp.toLocaleString('pt-BR'),'XP total']].map(([n,label])=>`<div class="panel profile-stat">${dots(n)}<p>${label}</p></div>`).join('')}</section><div class="section-heading"><h2>Conquistas</h2><span class="text-button">${achievements().filter(b=>b.unlocked).length} de ${achievements().length}</span></div><section class="panel badge-grid">${achievements().map((b,i)=>badgeButton(b,i,true)).join('')}</section><div class="section-heading"><h2>Configurações</h2></div><section class="panel settings-panel"><button class="setting" data-action="edit-profile">${icon('user')}<span>Editar perfil</span>${icon('chevron')}</button><button class="setting" data-action="notifications">${icon('bell')}<span>Notificações</span>${icon('chevron')}</button><button class="setting" data-action="theme" role="switch" aria-checked="${state.theme==='dark'}">${icon('moon')}<span>Tema escuro</span><span class="toggle ${state.theme==='dark'?'on':''}"></span></button></section>`;}
  const routes={inicio:{label:'Início',icon:'home',render:home},metas:{label:'Metas',icon:'target',render:goals},financas:{label:'Finanças',icon:'wallet',render:finance},perfil:{label:'Perfil',icon:'user',render:profile}};
  function render(transition=true){const next=location.hash.slice(1);const valid=routes[next]?next:'inicio',changed=valid!==route;route=valid;document.body.classList.toggle('theme-light',state.theme==='light');$('#page-subtitle').textContent=route==='inicio'?`Bom dia, ${state.name}`:routes[route].label;$('#header-action').innerHTML=route==='perfil'?icon('settings'):route==='financas'?`${monthLabel().replace(/^./,c=>c.toUpperCase())} <span>⌄</span>`:'Hoje <span>⌄</span>';$('#header-action').setAttribute('aria-label',route==='perfil'?'Editar perfil':route==='financas'?'Escolher mês':'Resumo de hoje');$('#screen').innerHTML=routes[route].render();$('.bottom-nav').innerHTML=Object.entries(routes).map(([key,r])=>`<a class="nav-item ${key===route?'active':''}" href="#${key}" aria-label="${r.label}" ${key===route?'aria-current="page"':''}>${icon(r.icon)}</a>`).join('');document.title=`${routes[route].label} · FORGE`;if(changed){$('#app-scroll').scrollTop=0;$('#screen').focus({preventScroll:true});}if(transition&&window.gsap&&!reduced()){gsap.fromTo('#screen > *',{y:13,opacity:0},{y:0,opacity:1,duration:.46,stagger:.045,ease:'power2.out',clearProps:'transform,opacity'});gsap.from('#screen .progress-fill',{scaleX:.12,duration:.9,delay:.16,ease:'power3.out',clearProps:'transform'});gsap.from('#screen .liquid',{scaleY:0,duration:1,stagger:.07,ease:'power2.out',clearProps:'transform'});} }
  const dialog=$('#sheet');
  function openSheet(html){$('#sheet-content').innerHTML=html;if(!dialog.open)dialog.showModal();if(window.gsap&&!reduced())gsap.fromTo(dialog,{y:90,opacity:0},{y:0,opacity:1,duration:.35,ease:'power3.out'});}
  function closeSheet(){dialog.close();}
  $('.close-sheet').addEventListener('click',closeSheet);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSheet();}});
  function quickActions(){openSheet(`<h2>Faça o dia contar.</h2><p>Escolha seu próximo passo.</p>${[['habits','checkbox','Meus hábitos'],['tasks','bars','Tarefas de hoje'],['transaction','wallet','Registrar transação'],['new-goal','target','Criar uma meta'],['new-habit','plus','Adicionar hábito']].map(([a,i,label])=>`<button class="quick-choice" data-action="${a}">${icon(i)}${label}${icon('chevron')}</button>`).join('')}`);}
  function taskSheet(){openSheet(`<h2>Tarefas de hoje</h2><p>${state.tasks.filter(t=>t.done).length} de ${state.tasks.length} concluídas.</p>${state.tasks.map(t=>`<button class="activity-row ${t.done?'done':''}" data-task="${t.id}" aria-pressed="${t.done}"><span class="checkbox">${t.done?icon('check'):''}</span><span class="activity-name">${esc(t.name)}</span></button>`).join('')}`);}
  function habitSheet(){openSheet(`<h2>Seus hábitos</h2><p>Pequenas ações, progresso real.</p>${state.habits.map(h=>`<div style="display:flex;gap:8px"><button class="activity-row ${h.done?'done':''}" data-habit="${h.id}" aria-pressed="${h.done}"><span class="checkbox">${h.done?icon('check'):''}</span>${art(h.art)}<span class="activity-name">${esc(h.name)}</span><span class="reward">+${h.reward} XP</span></button><button class="text-button" data-edit-habit="${h.id}" aria-label="Editar ${esc(h.name)}">Editar</button></div>`).join('')}<button class="primary-button" data-action="new-habit">Adicionar hábito</button>`);}
  function habitForm(id){const h=state.habits.find(h=>h.id===id);openSheet(`<h2>${h?'Editar':'Novo'} hábito</h2><p>Defina uma ação que cabe no seu dia.</p><form data-form="habit" data-id="${h?.id||''}"><label for="habit-name">Hábito e meta diária</label><input id="habit-name" name="name" maxlength="60" required value="${esc(h?.name||'')}" placeholder="Ex.: Ler 10 páginas"><label for="difficulty">Dificuldade</label><select name="reward" id="difficulty">${[[20,'Leve · 20 XP'],[40,'Moderada · 40 XP'],[60,'Desafiadora · 60 XP'],[80,'Intensa · 80 XP']].map(([v,l])=>`<option value="${v}" ${h?.reward===v?'selected':''}>${l}</option>`).join('')}</select><button class="primary-button">Salvar hábito</button></form>`);}
  function transactionForm(){openSheet(`<h2>Nova transação</h2><p>Clareza sobre seu dinheiro. +10 XP por registro.</p><form data-form="transaction"><div class="form-row"><div><label for="amount">Valor (R$)</label><input id="amount" name="amount" inputmode="decimal" type="number" step="0.01" min="0.01" max="100000000" placeholder="0,00" required></div><div><label for="type">Tipo</label><select id="type" name="type"><option value="expense">Saída</option><option value="income">Entrada</option></select></div></div><label for="description">Descrição</label><input id="description" name="name" maxlength="60" placeholder="Ex.: Mercado" required><div class="form-row"><div><label for="category">Categoria</label><select id="category" name="category">${['Comida','Transporte','Estudos','Lazer','Outros','Salário'].map(c=>`<option>${c}</option>`).join('')}</select></div><div><label for="date">Data</label><input id="date" name="date" type="date" value="${localDay()}" required></div></div><button class="primary-button">Adicionar transação</button></form>`);}
  function goalForm(){openSheet(`<h2>Sua próxima conquista.</h2><p>Transforme uma intenção em algo que você consegue medir.</p><form data-form="goal"><label for="goal-name">Nome da meta</label><input id="goal-name" name="name" maxlength="60" placeholder="Ex.: Guardar R$ 1.000" required><div class="form-row"><div><label for="goal-category">Categoria</label><select id="goal-category" name="category">${['Carreira','Finanças','Saúde','Estudos','Rotina'].map(c=>`<option>${c}</option>`).join('')}</select></div><div><label for="deadline">Prazo</label><input type="date" id="deadline" name="deadline" value="${localDay()}" required></div></div><div class="form-row"><div><label for="target">Objetivo numérico</label><input id="target" name="target" type="number" min="1" max="100000000" step="any" value="100" required></div><div><label for="unit">Unidade</label><select id="unit" name="unit"><option>%</option><option>R$</option><option>horas</option><option>módulos</option><option>dias</option></select></div></div><button class="primary-button">Criar meta · +300 XP ao concluir</button></form>`);}
  function goalDetail(id){const g=state.goals.find(g=>g.id===id);if(!g)return;openSheet(`<h2>${esc(g.name)}</h2><p>${esc(g.category)} · Até ${prettyDate(g.deadline)} · +${g.reward} XP ao concluir</p><div class="detail-progress">${progress(g.current/g.target*100)}</div><form data-form="goal-progress" data-id="${g.id}"><label for="current">Progresso acumulado (${esc(g.unit)})</label><input id="current" name="current" type="number" min="0" max="${g.target}" step="any" value="${g.current}" required ${g.completed?'disabled':''}><p style="margin-top:10px">Objetivo: ${g.target} ${esc(g.unit)}.</p><button class="primary-button" ${g.completed?'disabled':''}>${g.completed?'Meta concluída':'Salvar progresso · +30 XP por avanço'}</button></form>`);}
  function actions(action){if(action==='register')return quickActions();if(action==='transaction')return transactionForm();if(action==='tasks')return taskSheet();if(action==='habits')return habitSheet();if(action==='new-habit')return habitForm();if(action==='new-goal')return goalForm();if(action==='clear-category'){categoryFilter=null;render(false);return;}if(action==='theme'){state.theme=state.theme==='dark'?'light':'dark';save();render(false);return;}if(action==='edit-profile')return openSheet(`<h2>Seu personagem.</h2><p>Do seu jeito.</p><form data-form="profile"><label for="profile-name">Nome</label><input name="name" id="profile-name" maxlength="25" value="${esc(state.name)}" required><label for="handle">Nome de usuário</label><input name="handle" id="handle" maxlength="25" pattern="[a-zA-Z0-9_.]+" value="${esc(state.handle)}" required><label for="city">Cidade</label><input name="city" id="city" maxlength="45" value="${esc(state.city)}" required><button class="primary-button">Salvar perfil</button></form>`);if(action==='notifications')return openSheet(`<h2>Seu lembrete diário.</h2><p>Check-in às 8h e aviso de sequência às 21h. Neste protótipo, você pode salvar a preferência; o envio de notificações será conectado no app.</p><form data-form="notifications"><label for="notify">Lembretes</label><select id="notify" name="enabled"><option value="yes" ${state.notifications?'selected':''}>Ativados</option><option value="no" ${!state.notifications?'selected':''}>Desativados</option></select><button class="primary-button">Salvar preferência</button></form>`);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-habit],[data-task],[data-goal],[data-badge],[data-category],[data-edit-habit]');if(!b)return;if(b.dataset.action)return actions(b.dataset.action);if(b.dataset.editHabit)return habitForm(b.dataset.editHabit);if(b.dataset.habit){const h=state.habits.find(h=>h.id===b.dataset.habit);h.done=!h.done;earn(h.done?h.reward:-h.reward);save();if(dialog.open)habitSheet();render(false);toast(h.done?`+${h.reward} XP. Mais um passo dado!`:'Hábito desmarcado. XP ajustado.');if(window.gsap&&!reduced())gsap.from(`[data-habit="${h.id}"] .checkbox`,{scale:.6,duration:.5,ease:'back.out(3)'});return;}if(b.dataset.task){const t=state.tasks.find(t=>t.id===b.dataset.task);t.done=!t.done;save();taskSheet();render(false);return;}if(b.dataset.goal)return goalDetail(b.dataset.goal);if(b.dataset.category){categoryFilter=categoryFilter===b.dataset.category?null:b.dataset.category;render(false);return;}if(b.dataset.badge){const a=achievements()[Number(b.dataset.badge)];return openSheet(`<div class="badge-detail">${badge(a.type,!a.unlocked)}<h2>${a.name}</h2><p>${a.unlocked?'Conquista desbloqueada':'Próximo desafio'} · ${a.criterion}</p></div>`);}});
  $('#quick-action').addEventListener('click',()=>route==='metas'?goalForm():route==='financas'?transactionForm():quickActions());
  $('#header-action').addEventListener('click',()=>{if(route==='perfil')return actions('edit-profile');if(route==='financas')return openSheet(`<h2>Seu mês.</h2><p>Veja o saldo e as transações de cada período.</p><form data-form="month"><label for="month">Mês de referência</label><input id="month" name="month" type="month" value="${state.month}" required><button class="primary-button">Ver período</button></form>`);return openSheet(`<h2>Hoje conta.</h2><p>${new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p><p>${state.habits.filter(h=>h.done).length} de ${state.habits.length} hábitos concluídos. Sua sequência está em ${state.streak} dias.</p><button class="primary-button" data-action="habits">Ver meus hábitos</button>`);});
  document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('[data-form]'))return;e.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));let message='Salvo.';switch(form.dataset.form){case'transaction':{const amount=Number(data.amount);if(!Number.isFinite(amount)||amount<=0)return;state.transactions.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...data,amount});state.month=data.date.slice(0,7);earn(10);message='+10 XP. Transação registrada.';break;}case'goal':{state.goals.push({id:String(Date.now()),...data,target:Number(data.target),current:0,reward:300,art:data.category==='Finanças'?'coins':data.category==='Estudos'?'stack':'laptop',completed:false});message='Meta criada. Um objetivo de cada vez.';break;}case'goal-progress':{const g=state.goals.find(g=>g.id===form.dataset.id),n=Number(data.current);if(!g||g.completed||!Number.isFinite(n)||n<0||n>g.target)return;const increased=n>g.current;if(n===g.current){closeSheet();return;}g.current=n;if(increased)earn(30);if(n===g.target){g.completed=true;earn(g.reward);message=`Meta concluída! +${g.reward+30} XP.`;}else message=increased?'+30 XP. Seu progresso foi atualizado.':'Progresso corrigido.';break;}case'profile':{state.name=data.name.trim();state.handle=data.handle.trim();state.city=data.city.trim();message='Seu perfil foi atualizado.';break;}case'notifications':state.notifications=data.enabled==='yes';message='Preferência salva.';break;case'month':state.month=data.month;categoryFilter=null;break;case'habit':{const h=state.habits.find(h=>h.id===form.dataset.id);if(h){if(h.done)earn(Number(data.reward)-h.reward);h.name=data.name.trim();h.reward=Number(data.reward);}else state.habits.push({id:String(Date.now()),name:data.name.trim(),reward:Number(data.reward),art:'book',done:false});message='Hábito salvo.';break;}}
    save();closeSheet();render(false);toast(message);
  });
  addEventListener('hashchange',()=>render());render();save();
  if(window.ForgeEffects)ForgeEffects.init($('#energy-canvas'),{reducedMotion:reduced()});
  // Optional agent handoff tools. Safe no-op in browsers without WebMCP.
  if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tools=[
    {name:'read_forge_summary',title:'Resumo do FORGE',description:'Lê a tela atual e os totais demonstrativos do FORGE, sem alterar dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('Use um objeto vazio.');return {screen:route,level:level(),xp:state.xp,streak:state.streak,habitsCompleted:state.habits.filter(h=>h.done).length,habitsTotal:state.habits.length,finances:finances()};}},
    {name:'navigate_forge_screen',title:'Abrir tela do FORGE',description:'Navega para uma das quatro telas do protótipo, sem registrar ações nem alterar XP.',inputSchema:{type:'object',properties:{screen:{type:'string',enum:Object.keys(routes)}},required:['screen'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Object.hasOwn(routes,input.screen)||Object.keys(input).some(k=>k!=='screen'))throw new Error('Tela inválida.');history.replaceState(null,'','#'+input.screen);render();return{screen:route};}}
  ];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
